# Generated by Django 3.0.4 on 2020-03-11 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_memo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memo',
        ),
    ]
